### PR TITLE
Simplified Database Connection Code (db.js) and Solved Image Not Loading On Home Page Problem

### PR DESCRIPTION
**Pull request by Royalatomo**
Did) I have updated "/server/db.js" so that it is more readable and I have made "index.js" compatible with "db.js"
Sol) It made it more clear to read and removed unwanted code so that it looks more clear in reading.
Screenshot from 2021-10-01 13-19-31

Did) I have updated "/DB Collections/productops.js" and "/Models/Product.js" and "Client: /Components/Product.js"
Sol) It solved the problem because you forgot to add a field of "image" while storing the new product in the database and I removed "." from  from react component so that the user can also add images from outside as well as inside the project.

Screenshot from 2021-10-01 13-33-40

I have found many bugs If you like can I show the bug to you and I also found their solution so if you like I could make other pull requests if you like ... (I have Four other Pull request in mind which I will do If you like"

### CODE REVIEW

**Comment by rakesh820** [comment]
I really liked the updates you have done. You can make any changes you want, to resolve the bugs.

**Comment by rakesh820** [comment]
You can make all the pull requests you want, for resolving those bugs.

**Comment by Royalatomo** [comment]
Can You Add These Tags(Topics)  In  your repo so that I can take part in
the contest as well as work on your project: Tags:-> hacktoberfest,
hacktoberfest2021, hacktoberfest-accepted
[image: Screenshot from 2021-10-01 16-21-13.png]

**Comment by Royalatomo** [comment]
The things I like to do if you allow me to work on your project:-

1) Commenting all code
2) fixing bugs (product buying problem, cart problems)
3) fixing warnings, etc
4) give admin of the website a page where he can add new items without
having to use Api directly

**Pull request merged**
